### ISSUE TITLE
Error: lpt@0.2.3 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by gboslee** [DeniSix/node-lpt#5]
Hello.
I can not install, so log.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/iojs', '/usr/bin/npm', 'i', 'lpt' ]
2 info using npm@2.8.3
3 info using node@v1.7.1
4 verbose install initial load of /home/gboslee/workspace/lpt/package.json
5 verbose readDependencies loading dependencies from /home/gboslee/workspace/lpt/package.json
6 silly cache add args [ 'lpt', null ]
7 verbose cache add spec lpt
8 silly cache add parsed spec { raw: 'lpt',
8 silly cache add   scope: null,
8 silly cache add   name: 'lpt',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed lpt@*
10 verbose addNamed "*" is a valid semver range for lpt
11 silly addNameRange { name: 'lpt', range: '*', hasData: false }
12 silly mapToRegistry name lpt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/lpt
16 verbose addNameRange registry:https://registry.npmjs.org/lpt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/lpt
18 verbose request no auth needed
19 info attempt registry request try #1 at 15:05:50
20 verbose request id 0d7727a8d6d768b9
21 verbose etag "3AQ6FU4EKJFPEQD1GYWRL961H"
22 http request GET https://registry.npmjs.org/lpt
23 http 304 https://registry.npmjs.org/lpt
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 17 Apr 2015 10:05:50 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Fri, 17 Apr 2015 10:05:50 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"3AQ6FU4EKJFPEQD1GYWRL961H"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-fra1243-FRA',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1429265150.633237,VS0,VE182',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/lpt from cache
26 verbose get saving lpt to /home/gboslee/.npm/registry.npmjs.org/lpt/.cache.json
27 silly addNameRange number 2 { name: 'lpt', range: '*', hasData: true }
28 silly addNameRange versions [ 'lpt', [ '0.1.0', '0.2.0', '0.2.2', '0.2.3' ] ]
29 silly addNamed lpt@0.2.3
30 verbose addNamed "0.2.3" is a plain semver version for lpt
31 silly cache afterAdd lpt@0.2.3
32 verbose afterAdd /home/gboslee/.npm/lpt/0.2.3/package/package.json not in flight; writing
33 verbose afterAdd /home/gboslee/.npm/lpt/0.2.3/package/package.json written
34 silly install resolved [ { name: 'lpt',
34 silly install resolved     version: '0.2.3',
34 silly install resolved     description: 'High level binding to deal with parallel ports (linux only)',
34 silly install resolved     author: { name: 'Denis Shemanaev', email: 'denis@shemanaev.com' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     keywords: [ 'parallel port', 'lpt', 'printer' ],
34 silly install resolved     homepage: 'https://github.com/DeniSix/node-lpt',
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/DeniSix/node-lpt.git' },
34 silly install resolved     engines: { node: '>= 0.8.0' },
34 silly install resolved     main: './build/Release/lpt',
34 silly install resolved     scripts: { install: 'node-gyp rebuild' },
34 silly install resolved     gypfile: true,
34 silly install resolved     gitHead: 'f21304e83c6b3f7bea7bf6fc1a437a6b275bfc4f',
34 silly install resolved     bugs: { url: 'https://github.com/DeniSix/node-lpt/issues' },
34 silly install resolved     _id: 'lpt@0.2.3',
34 silly install resolved     _shasum: '19dc4a261e3e4c023dda431e088e813d1227bbc4',
34 silly install resolved     _from: 'lpt@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'denisix', email: 'denis.shemanaev@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '19dc4a261e3e4c023dda431e088e813d1227bbc4',
34 silly install resolved        tarball: 'http://registry.npmjs.org/lpt/-/lpt-0.2.3.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/lpt/-/lpt-0.2.3.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install lpt@0.2.3 into /home/gboslee/workspace/lpt
36 info installOne lpt@0.2.3
37 verbose installOne of lpt to /home/gboslee/workspace/lpt not in flight; installing
38 verbose lock using /home/gboslee/.npm/_locks/lpt-38d9e8ee2086ff5e.lock for /home/gboslee/workspace/lpt/node_modules/lpt
39 silly install write writing lpt 0.2.3 to /home/gboslee/workspace/lpt/node_modules/lpt
40 verbose unbuild node_modules/lpt
41 silly gentlyRm /home/gboslee/workspace/lpt/node_modules/lpt is being purged from base /home/gboslee/workspace/lpt
42 verbose gentlyRm don't care about contents; nuking /home/gboslee/workspace/lpt/node_modules/lpt
43 verbose tar unpack /home/gboslee/.npm/lpt/0.2.3/package.tgz
44 verbose tar unpacking to /home/gboslee/workspace/lpt/node_modules/lpt
45 silly gentlyRm /home/gboslee/workspace/lpt/node_modules/lpt is being purged
46 verbose gentlyRm don't care about contents; nuking /home/gboslee/workspace/lpt/node_modules/lpt
47 silly gunzTarPerm modes [ '775', '664' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm modified mode [ 'package.json', 438, 436 ]
50 silly gunzTarPerm extractEntry .npmignore
51 silly gunzTarPerm modified mode [ '.npmignore', 438, 436 ]
52 silly gunzTarPerm extractEntry README.md
53 silly gunzTarPerm modified mode [ 'README.md', 438, 436 ]
54 silly gunzTarPerm extractEntry LICENSE.txt
55 silly gunzTarPerm modified mode [ 'LICENSE.txt', 438, 436 ]
56 silly gunzTarPerm extractEntry binding.gyp
57 silly gunzTarPerm modified mode [ 'binding.gyp', 438, 436 ]
58 silly gunzTarPerm extractEntry src/binding.cc
59 silly gunzTarPerm modified mode [ 'src/binding.cc', 438, 436 ]
60 silly gunzTarPerm extractEntry src/node-helpers.h
61 silly gunzTarPerm modified mode [ 'src/node-helpers.h', 438, 436 ]
62 silly gunzTarPerm extractEntry src/port-control.cc
63 silly gunzTarPerm modified mode [ 'src/port-control.cc', 438, 436 ]
64 silly gunzTarPerm extractEntry src/port-control.h
65 silly gunzTarPerm modified mode [ 'src/port-control.h', 438, 436 ]
66 silly gunzTarPerm extractEntry src/port-status.cc
67 silly gunzTarPerm modified mode [ 'src/port-status.cc', 438, 436 ]
68 silly gunzTarPerm extractEntry src/port-status.h
69 silly gunzTarPerm modified mode [ 'src/port-status.h', 438, 436 ]
70 silly gunzTarPerm extractEntry src/port.cc
71 silly gunzTarPerm modified mode [ 'src/port.cc', 438, 436 ]
72 silly gunzTarPerm extractEntry src/port.h
73 silly gunzTarPerm modified mode [ 'src/port.h', 438, 436 ]
74 verbose write writing to /home/gboslee/workspace/lpt/node_modules/lpt/package.json
75 info preinstall lpt@0.2.3
76 verbose readDependencies loading dependencies from /home/gboslee/workspace/lpt/node_modules/lpt/package.json
77 verbose readDependencies loading dependencies from /home/gboslee/workspace/lpt/node_modules/lpt/package.json
78 silly install resolved []
79 verbose about to build /home/gboslee/workspace/lpt/node_modules/lpt
80 info build /home/gboslee/workspace/lpt/node_modules/lpt
81 info linkStuff lpt@0.2.3
82 silly linkStuff lpt@0.2.3 has /home/gboslee/workspace/lpt/node_modules as its parent node_modules
83 verbose linkBins lpt@0.2.3
84 verbose linkMans lpt@0.2.3
85 verbose rebuildBundles lpt@0.2.3
86 info install lpt@0.2.3
87 verbose unsafe-perm in lifecycle true
88 info lpt@0.2.3 Failed to exec install script
89 verbose unlock done using /home/gboslee/.npm/_locks/lpt-38d9e8ee2086ff5e.lock for /home/gboslee/workspace/lpt/node_modules/lpt
90 verbose stack Error: lpt@0.2.3 install: `node-gyp rebuild`
90 verbose stack Exit status 1
90 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
90 verbose stack     at emitTwo (events.js:87:13)
90 verbose stack     at EventEmitter.emit (events.js:169:7)
90 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
90 verbose stack     at emitTwo (events.js:87:13)
90 verbose stack     at ChildProcess.emit (events.js:169:7)
90 verbose stack     at maybeClose (child_process.js:953:16)
90 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1022:5)
91 verbose pkgid lpt@0.2.3
92 verbose cwd /home/gboslee/workspace/lpt
93 error Linux 3.13.0-51-generic
94 error argv "/usr/bin/iojs" "/usr/bin/npm" "i" "lpt"
95 error node v1.7.1
96 error npm  v2.8.3
97 error code ELIFECYCLE
98 error lpt@0.2.3 install: `node-gyp rebuild`
98 error Exit status 1
99 error Failed at the lpt@0.2.3 install script 'node-gyp rebuild'.
99 error This is most likely a problem with the lpt package,
99 error not with npm itself.
99 error Tell the author that this fails on your system:
99 error     node-gyp rebuild
99 error You can get their info via:
99 error     npm owner ls lpt
99 error There is likely additional logging output above.
100 verbose exit [ 1, true ]
101 verbose unbuild node_modules/lpt
102 info preuninstall lpt@0.2.3
103 info uninstall lpt@0.2.3
104 verbose unbuild rmStuff lpt@0.2.3 from /home/gboslee/workspace/lpt/node_modules
105 info postuninstall lpt@0.2.3
106 silly gentlyRm /home/gboslee/workspace/lpt/node_modules/lpt is being purged from base /home/gboslee/workspace/lpt
107 verbose gentlyRm don't care about contents; nuking /home/gboslee/workspace/lpt/node_modules/lpt
108 silly vacuum-fs purging /home/gboslee/workspace/lpt/node_modules/lpt
109 silly vacuum-fs removing /home/gboslee/workspace/lpt/node_modules
110 silly vacuum-fs finished vacuuming up to /home/gboslee/workspace/lpt

**Comment by DeniSix** [comment]
Well, node 0.12 (and iojs respectively) introduced alot of breaking changes in native addons API, so module needs to be ported to [iojs/nan](https://github.com/iojs/nan).
Put it in my todo list but no estimates on fixing.
If you really need lpt working right now just use `node 0.10` via [`nvm`](https://github.com/creationix/nvm) or something.

**Comment by DeniSix** [comment]
Version `0.3` had to fix this
